name: Tool Releases

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  publish:
    name: Build and Publish all Tools
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: Build all tools
      shell: pwsh
      run: |
          cd tools
          mkdir out
          ls
          gci build.bat -r | % { pushd $_.DirectoryName; & $_.FullName; popd }
          gci *.exe -r | mi -dest (join-path $pwd out)
          ls out/
    - name: Upload built tools to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: tools/out/*.exe
        file_glob: true
